# Generated by Django 4.0.2 on 2022-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(max_length=128, verbose_name='磁盘型号'),
        ),
    ]
